# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.1.1

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - curl -X DELETE "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads/version.dat"
          - apt-get update
          - apt-get -qq install git
          - echo ${BITBUCKET_BUILD_NUMBER}-${BITBUCKET_COMMIT} >> version.dat
          # AUTO VERSIONING
          - git config remote.origin.url https://${BB_AUTH_STRING}@bitbucket.org/$USER_NAME/password-tool.git
          - git config --global push.default matching
          - git init
          - git config user.name "<$USER_NAME>"
          - git config user.email "<$USER_EMAIL>"
          - git add version.dat
          - git commit -m "[skip CI]"
          - git push
          - echo ${BITBUCKET_BUILD_NUMBER}-${BITBUCKET_COMMIT} >> version.dat
          - git archive --format zip --output ${BITBUCKET_BUILD_NUMBER}-${BITBUCKET_COMMIT}.zip master 
          - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"version.dat"
          - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"${BITBUCKET_BUILD_NUMBER}-${BITBUCKET_COMMIT}.zip"
        deployment:
         production
